version: "3.8"

services:
  roadev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roadev
    # depends_on:
    #   - db
    environment:
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY:-empty}"
    networks:
      - roadev-network
    volumes:
      - roadev-volume:/usr/src

networks:
  roadev-network:
    driver: bridge

volumes:
  roadev-volume:
    driver: local
