version: "3.8"

services:
  roadev:
    image: alexiscrack3/roadev:latest

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/nginx.dockerfile
    container_name: nginx
    restart: always
    depends_on:
      - roadev
    ports:
      - 80:80
    networks:
      - roadev-network
