version: "3.8"

services:
  roadev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roadev
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - roadev-network

  db:
    image: postgres:14-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - roadev-network
    volumes:
      - roadev-volume:/var/lib/postgresql/data

networks:
  roadev-network:
    driver: bridge

volumes:
  roadev-volume:
    driver: local
