version: "3.8"

services:
  roadev:
    container_name: roadev
    depends_on:
      - db
    env_file:
      - .docker/base/.env.rails
      - .docker/base/.env.db
    networks:
      - roadev-network
      - data-network
    volumes:
      - roadev-volume:/usr/src/public

  db:
    image: postgres:14-alpine
    container_name: db
    env_file:
      - .docker/base/.env.db
    ports:
      - 5432:5432
    networks:
      - data-network
    volumes:
      - data-volume:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:1.21.4-alpine
    container_name: nginx
    # command: [nginx-debug, '-g', 'daemon off;']
    restart: always
    depends_on:
      - roadev
    ports:
      - 80:80
    networks:
      - roadev-network
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - roadev-volume:/usr/share/nginx/html/public

networks:
  roadev-network:
    driver: bridge
  data-network:
    driver: bridge

volumes:
  roadev-volume:
    driver: local
  data-volume:
    driver: local
