name: Unit Tests CI

on:
  push:
    branches: [ main ]

jobs:

  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout files
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        # Not needed with a .ruby-version file
        ruby-version: 2.6.3
        # runs 'bundle install' and caches installed gems automatically
        bundler-cache: true

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.18.3

    - name: Set up Yarn
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - name: Install dependencies
      run: |
        bin/rails webpacker:compile

    - name: Run tests
      run: |
        bin/rails test

